dist: xenial
language: python
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
  allow_failures:
    - python: 3.8-dev
  fast_finish: true
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov --file .tox/3.6/log/coverage.xml
deploy:
  provider: pypi
  user: TimofeyKukushkin
  password:
    secure: abtSZuSyAU6lhYsgeRxGGnfhKQ0R9lTdDu2r8ZEFVJwaOpjqSVEMsBk1pa9Gc/OXh6M7r61wsPJYwh50aaqA5BQfujcm15xCcElx88l6+E9R9aUrZgrZQdFJ2FYN83rrLm6q1GPWMFB4KgQJTVMdW+F6plINNbicj4RhXVcC2pNJwSRECdrAcuPoojhCGZJOySotZbbuKX7QGGNzNvrERz5PmvdKWQEA7IUtLZCRktS00iyKjNpkZLcvkhCS+4OXAwX5a5kIZLtniDHF5EqOFCpLxkHmCs+RLJ5RcHPGqO9KRkSv/pf05H/J+8g7VKUVoNy74Fi8kKb1P5blaIwtXO5ZkzGPuTtJ02lXzIdFB/qotN2lnNDX/lavPsjiV7CU2fZaE/u4jlLfgmRx77l4H7s1lndc7jCbcHkKYZPfAe++QclkpFvM2BebKNmn8a/e7JAsIaWIR4czRbFvur7TzXwiDyfU0WN74lk9neJ5g7k9mIPhUMoY2o4UEUsmltsx9ZYSp8ClXDm1nqYpcWmCjjSVIagKA5kz+X1KHtArW/4sQ3Yc0tCVoccTJNrST6barmktZkqd+juFkhmleYMKhFKvLfO/TyqO+wkHlkIEmRyQuXcTj88K+CMwiiQs1mRJToMJA9igUSKgnCKjRZlVP5GdRPvRpbZkIviVhdFyJMc=
  on:
    tags: true
    python: '2.7'
  distributions: sdist bdist_wheel
  skip_existing: true
